"""HTML report generation for backtest results."""
from datetime import datetime
from pathlib import Path
from typing import List

from raj.backtest.engine import BacktestResult
from raj.visualization.charts import ChartGenerator


class ReportGenerator:
    """Generate HTML reports for backtest results."""

    @staticmethod
    def generate_backtest_report(
        result: BacktestResult,
        output_path: str
    ) -> str:
        """Generate comprehensive HTML report for a single backtest.

        Args:
            result: BacktestResult object
            output_path: Path for output HTML file

        Returns:
            Path to generated report
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Create dashboard chart
        dashboard = ChartGenerator.create_dashboard(result)

        # Get chart HTML
        chart_html = dashboard.to_html(include_plotlyjs='cdn', div_id='dashboard')

        # Create metrics table HTML
        metrics_html = ReportGenerator._create_metrics_table(result.metrics)

        # Create trades table HTML
        trades_html = ReportGenerator._create_trades_table(result.trades)

        # Combine into full HTML
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Backtest Report - {result.strategy_name}</title>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    margin: 20px;
                    background-color: #f5f5f5;
                }}
                .container {{
                    max-width: 1400px;
                    margin: 0 auto;
                    background-color: white;
                    padding: 30px;
                    box-shadow: 0 0 10px rgba(0,0,0,0.1);
                }}
                h1 {{
                    color: #333;
                    border-bottom: 3px solid #4CAF50;
                    padding-bottom: 10px;
                }}
                h2 {{
                    color: #555;
                    margin-top: 30px;
                    border-bottom: 2px solid #ddd;
                    padding-bottom: 5px;
                }}
                table {{
                    width: 100%;
                    border-collapse: collapse;
                    margin: 20px 0;
                }}
                th, td {{
                    padding: 12px;
                    text-align: left;
                    border-bottom: 1px solid #ddd;
                }}
                th {{
                    background-color: #4CAF50;
                    color: white;
                }}
                tr:hover {{
                    background-color: #f5f5f5;
                }}
                .positive {{
                    color: green;
                }}
                .negative {{
                    color: red;
                }}
                .footer {{
                    margin-top: 30px;
                    padding-top: 20px;
                    border-top: 1px solid #ddd;
                    color: #888;
                    font-size: 12px;
                }}
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Backtest Report: {result.strategy_name}</h1>
                <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>

                <h2>Performance Metrics</h2>
                {metrics_html}

                <h2>Performance Dashboard</h2>
                {chart_html}

                <h2>Trade History ({len(result.trades)} trades)</h2>
                {trades_html}

                <div class="footer">
                    <p>Report generated by Raj Trading System</p>
                </div>
            </div>
        </body>
        </html>
        """

        # Write to file
        with open(output_path, 'w') as f:
            f.write(html_content)

        return str(output_path)

    @staticmethod
    def _create_metrics_table(metrics: dict) -> str:
        """Create HTML table for metrics.

        Args:
            metrics: Dictionary of metrics

        Returns:
            HTML string
        """
        def format_value(key, value):
            if 'pct' in key.lower() or 'rate' in key.lower() or 'return' in key.lower():
                return f"{value:.2f}%"
            elif 'ratio' in key.lower() or 'factor' in key.lower():
                return f"{value:.2f}"
            elif isinstance(value, float):
                return f"${value:,.2f}"
            else:
                return str(value)

        def get_class(key, value):
            if isinstance(value, (int, float)) and 'pct' in key.lower():
                return 'positive' if value > 0 else 'negative'
            return ''

        html = "<table>\n"
        html += "  <tr><th>Metric</th><th>Value</th></tr>\n"

        for key, value in metrics.items():
            formatted_key = key.replace('_', ' ').title()
            formatted_value = format_value(key, value)
            css_class = get_class(key, value)

            html += f"  <tr><td>{formatted_key}</td><td class='{css_class}'>{formatted_value}</td></tr>\n"

        html += "</table>\n"
        return html

    @staticmethod
    def _create_trades_table(trades: list) -> str:
        """Create HTML table for trade history.

        Args:
            trades: List of Trade objects

        Returns:
            HTML string
        """
        if len(trades) == 0:
            return "<p>No trades executed.</p>"

        html = "<table>\n"
        html += "  <tr><th>Symbol</th><th>Entry Date</th><th>Exit Date</th>"
        html += "<th>Entry Price</th><th>Exit Price</th><th>Quantity</th>"
        html += "<th>P&L</th><th>P&L %</th></tr>\n"

        for trade in trades:
            pnl_class = 'positive' if trade.pnl > 0 else 'negative'

            html += f"  <tr>"
            html += f"<td>{trade.symbol}</td>"
            html += f"<td>{trade.entry_date.strftime('%Y-%m-%d')}</td>"
            html += f"<td>{trade.exit_date.strftime('%Y-%m-%d')}</td>"
            html += f"<td>${trade.entry_price:.2f}</td>"
            html += f"<td>${trade.exit_price:.2f}</td>"
            html += f"<td>{trade.quantity}</td>"
            html += f"<td class='{pnl_class}'>${trade.pnl:.2f}</td>"
            html += f"<td class='{pnl_class}'>{trade.pnl_pct:.2f}%</td>"
            html += f"</tr>\n"

        html += "</table>\n"
        return html

    @staticmethod
    def generate_comparison_report(
        results: List[BacktestResult],
        output_path: str
    ) -> str:
        """Generate comparison report for multiple backtests.

        Args:
            results: List of BacktestResult objects
            output_path: Path for output HTML file

        Returns:
            Path to generated report
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Create comparison table
        comparison_html = ReportGenerator._create_comparison_table(results)

        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Strategy Comparison Report</title>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    margin: 20px;
                    background-color: #f5f5f5;
                }}
                .container {{
                    max-width: 1400px;
                    margin: 0 auto;
                    background-color: white;
                    padding: 30px;
                    box-shadow: 0 0 10px rgba(0,0,0,0.1);
                }}
                h1 {{
                    color: #333;
                    border-bottom: 3px solid #4CAF50;
                    padding-bottom: 10px;
                }}
                table {{
                    width: 100%;
                    border-collapse: collapse;
                    margin: 20px 0;
                }}
                th, td {{
                    padding: 12px;
                    text-align: left;
                    border-bottom: 1px solid #ddd;
                }}
                th {{
                    background-color: #4CAF50;
                    color: white;
                }}
                tr:hover {{
                    background-color: #f5f5f5;
                }}
                .positive {{
                    color: green;
                }}
                .negative {{
                    color: red;
                }}
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Strategy Comparison Report</h1>
                <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                <p><strong>Strategies Compared:</strong> {len(results)}</p>

                {comparison_html}
            </div>
        </body>
        </html>
        """

        with open(output_path, 'w') as f:
            f.write(html_content)

        return str(output_path)

    @staticmethod
    def _create_comparison_table(results: List[BacktestResult]) -> str:
        """Create comparison table for multiple strategies.

        Args:
            results: List of BacktestResult objects

        Returns:
            HTML string
        """
        html = "<table>\n"
        html += "  <tr><th>Strategy</th><th>Total Return</th><th>Annualized Return</th>"
        html += "<th>Sharpe Ratio</th><th>Max Drawdown</th><th>Win Rate</th><th># Trades</th></tr>\n"

        for result in results:
            m = result.metrics
            total_return_class = 'positive' if m['total_return'] > 0 else 'negative'

            html += f"  <tr>"
            html += f"<td><strong>{result.strategy_name}</strong></td>"
            html += f"<td class='{total_return_class}'>{m['total_return']:.2f}%</td>"
            html += f"<td>{m['annualized_return']:.2f}%</td>"
            html += f"<td>{m['sharpe_ratio']:.2f}</td>"
            html += f"<td class='negative'>{m['max_drawdown']:.2f}%</td>"
            html += f"<td>{m['win_rate']:.2f}%</td>"
            html += f"<td>{m['num_trades']}</td>"
            html += f"</tr>\n"

        html += "</table>\n"
        return html
